# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer Files\filterkitwidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterWindow(object):
    def setupUi(self, FilterWindow):
        FilterWindow.setObjectName("FilterWindow")
        FilterWindow.resize(541, 149)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FilterWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filterKitBox = QtWidgets.QGroupBox(FilterWindow)
        self.filterKitBox.setObjectName("filterKitBox")
        self.gridLayout = QtWidgets.QGridLayout(self.filterKitBox)
        self.gridLayout.setObjectName("gridLayout")
        self.filterLowpassBessel = QtWidgets.QRadioButton(self.filterKitBox)
        self.filterLowpassBessel.setChecked(True)
        self.filterLowpassBessel.setObjectName("filterLowpassBessel")
        self.gridLayout.addWidget(self.filterLowpassBessel, 0, 0, 1, 1)
        self.filterBandstopBessel = QtWidgets.QRadioButton(self.filterKitBox)
        self.filterBandstopBessel.setObjectName("filterBandstopBessel")
        self.gridLayout.addWidget(self.filterBandstopBessel, 0, 1, 1, 1)
        self.filterGaussian = QtWidgets.QRadioButton(self.filterKitBox)
        self.filterGaussian.setObjectName("filterGaussian")
        self.gridLayout.addWidget(self.filterGaussian, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.filterKitBox)
        self.groupBox.setEnabled(False)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.filterGaussianSigma = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.filterGaussianSigma.setDecimals(1)
        self.filterGaussianSigma.setMaximum(100000000000.0)
        self.filterGaussianSigma.setProperty("value", 20.0)
        self.filterGaussianSigma.setObjectName("filterGaussianSigma")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filterGaussianSigma)
        self.gridLayout.addWidget(self.groupBox, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.filterKitBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.besselLowpassOrder = QtWidgets.QSpinBox(self.groupBox_2)
        self.besselLowpassOrder.setMinimum(1)
        self.besselLowpassOrder.setMaximum(16)
        self.besselLowpassOrder.setObjectName("besselLowpassOrder")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.besselLowpassOrder)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.besselCutoffFreq = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.besselCutoffFreq.setDecimals(3)
        self.besselCutoffFreq.setMinimum(0.0)
        self.besselCutoffFreq.setMaximum(1000.0)
        self.besselCutoffFreq.setProperty("value", 25.0)
        self.besselCutoffFreq.setObjectName("besselCutoffFreq")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.besselCutoffFreq)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.filterKitBox)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.besselBandstopOrder = QtWidgets.QSpinBox(self.groupBox_3)
        self.besselBandstopOrder.setMinimum(1)
        self.besselBandstopOrder.setMaximum(16)
        self.besselBandstopOrder.setProperty("value", 2)
        self.besselBandstopOrder.setObjectName("besselBandstopOrder")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.besselBandstopOrder)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.besselBandstopLow = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.besselBandstopLow.setDecimals(3)
        self.besselBandstopLow.setMinimum(0.0)
        self.besselBandstopLow.setMaximum(1000000.0)
        self.besselBandstopLow.setProperty("value", 39.055)
        self.besselBandstopLow.setObjectName("besselBandstopLow")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.besselBandstopLow)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.besselBandstopHigh = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.besselBandstopHigh.setDecimals(3)
        self.besselBandstopHigh.setMinimum(0.0)
        self.besselBandstopHigh.setMaximum(1000000.0)
        self.besselBandstopHigh.setProperty("value", 39.07)
        self.besselBandstopHigh.setObjectName("besselBandstopHigh")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.besselBandstopHigh)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.filterKitBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterPreviewBtn = QtWidgets.QPushButton(FilterWindow)
        self.filterPreviewBtn.setObjectName("filterPreviewBtn")
        self.verticalLayout.addWidget(self.filterPreviewBtn)
        self.filterApplyBtn = QtWidgets.QPushButton(FilterWindow)
        self.filterApplyBtn.setObjectName("filterApplyBtn")
        self.verticalLayout.addWidget(self.filterApplyBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_2.setBuddy(self.besselLowpassOrder)
        self.label.setBuddy(self.besselCutoffFreq)
        self.label_3.setBuddy(self.besselLowpassOrder)
        self.label_4.setBuddy(self.besselCutoffFreq)
        self.label_5.setBuddy(self.besselCutoffFreq)

        self.retranslateUi(FilterWindow)
        self.filterLowpassBessel.toggled['bool'].connect(self.groupBox_2.setEnabled)
        self.filterGaussian.toggled['bool'].connect(self.groupBox.setEnabled)
        self.filterBandstopBessel.toggled['bool'].connect(self.groupBox_3.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FilterWindow)
        FilterWindow.setTabOrder(self.filterLowpassBessel, self.filterBandstopBessel)
        FilterWindow.setTabOrder(self.filterBandstopBessel, self.filterGaussian)
        FilterWindow.setTabOrder(self.filterGaussian, self.besselLowpassOrder)
        FilterWindow.setTabOrder(self.besselLowpassOrder, self.besselCutoffFreq)
        FilterWindow.setTabOrder(self.besselCutoffFreq, self.besselBandstopOrder)
        FilterWindow.setTabOrder(self.besselBandstopOrder, self.besselBandstopLow)
        FilterWindow.setTabOrder(self.besselBandstopLow, self.besselBandstopHigh)
        FilterWindow.setTabOrder(self.besselBandstopHigh, self.filterGaussianSigma)
        FilterWindow.setTabOrder(self.filterGaussianSigma, self.filterPreviewBtn)
        FilterWindow.setTabOrder(self.filterPreviewBtn, self.filterApplyBtn)

    def retranslateUi(self, FilterWindow):
        _translate = QtCore.QCoreApplication.translate
        FilterWindow.setWindowTitle(_translate("FilterWindow", "Filter "))
        self.filterKitBox.setTitle(_translate("FilterWindow", "Create Filter"))
        self.filterLowpassBessel.setText(_translate("FilterWindow", "Bessel (LP)"))
        self.filterBandstopBessel.setText(_translate("FilterWindow", "Bessel (band-stop)"))
        self.filterGaussian.setText(_translate("FilterWindow", "Gaussian (LP)"))
        self.label_6.setText(_translate("FilterWindow", "sigma"))
        self.filterGaussianSigma.setSuffix(_translate("FilterWindow", " us"))
        self.label_2.setText(_translate("FilterWindow", "order"))
        self.label.setText(_translate("FilterWindow", "cutoff "))
        self.besselCutoffFreq.setSuffix(_translate("FilterWindow", " kHz"))
        self.label_3.setText(_translate("FilterWindow", "order"))
        self.label_4.setText(_translate("FilterWindow", "low cutoff"))
        self.besselBandstopLow.setSuffix(_translate("FilterWindow", " kHz"))
        self.label_5.setText(_translate("FilterWindow", "high cutoff"))
        self.besselBandstopHigh.setSuffix(_translate("FilterWindow", " kHz"))
        self.filterPreviewBtn.setText(_translate("FilterWindow", "Preview..."))
        self.filterApplyBtn.setText(_translate("FilterWindow", "Apply"))
