# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer Files\peaktoolkitwidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_peakWidget(object):
    def setupUi(self, peakWidget):
        peakWidget.setObjectName("peakWidget")
        peakWidget.resize(239, 311)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(peakWidget.sizePolicy().hasHeightForWidth())
        peakWidget.setSizePolicy(sizePolicy)
        peakWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.formLayout = QtWidgets.QFormLayout(peakWidget)
        self.formLayout.setObjectName("formLayout")
        self.peakTypeBox = QtWidgets.QGroupBox(peakWidget)
        self.peakTypeBox.setObjectName("peakTypeBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.peakTypeBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.peakTypeRising = QtWidgets.QRadioButton(self.peakTypeBox)
        self.peakTypeRising.setChecked(True)
        self.peakTypeRising.setObjectName("peakTypeRising")
        self.horizontalLayout.addWidget(self.peakTypeRising)
        self.peakTypeFalling = QtWidgets.QRadioButton(self.peakTypeBox)
        self.peakTypeFalling.setObjectName("peakTypeFalling")
        self.horizontalLayout.addWidget(self.peakTypeFalling)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.peakTypeBox)
        self.label = QtWidgets.QLabel(peakWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(peakWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.peakLowerBoundCheck = QtWidgets.QCheckBox(peakWidget)
        self.peakLowerBoundCheck.setChecked(True)
        self.peakLowerBoundCheck.setObjectName("peakLowerBoundCheck")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.peakLowerBoundCheck)
        self.peakLowerBound = QtWidgets.QDoubleSpinBox(peakWidget)
        self.peakLowerBound.setMinimum(-500.0)
        self.peakLowerBound.setMaximum(500.0)
        self.peakLowerBound.setProperty("value", -10.0)
        self.peakLowerBound.setObjectName("peakLowerBound")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.peakLowerBound)
        self.peakUpperBoundCheck = QtWidgets.QCheckBox(peakWidget)
        self.peakUpperBoundCheck.setChecked(True)
        self.peakUpperBoundCheck.setObjectName("peakUpperBoundCheck")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.peakUpperBoundCheck)
        self.peakUpperBound = QtWidgets.QDoubleSpinBox(peakWidget)
        self.peakUpperBound.setMinimum(-300.0)
        self.peakUpperBound.setMaximum(300.0)
        self.peakUpperBound.setObjectName("peakUpperBound")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.peakUpperBound)
        self.widthMinCheck = QtWidgets.QCheckBox(peakWidget)
        self.widthMinCheck.setChecked(True)
        self.widthMinCheck.setObjectName("widthMinCheck")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.widthMinCheck)
        self.widthMin = QtWidgets.QDoubleSpinBox(peakWidget)
        self.widthMin.setMaximum(10000000000.0)
        self.widthMin.setSingleStep(5.0)
        self.widthMin.setObjectName("widthMin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.widthMin)
        self.widthMaxCheck = QtWidgets.QCheckBox(peakWidget)
        self.widthMaxCheck.setChecked(True)
        self.widthMaxCheck.setObjectName("widthMaxCheck")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.widthMaxCheck)
        self.widthMax = QtWidgets.QDoubleSpinBox(peakWidget)
        self.widthMax.setMaximum(1000000000.0)
        self.widthMax.setSingleStep(5.0)
        self.widthMax.setObjectName("widthMax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.widthMax)
        self.relHeightCheck = QtWidgets.QCheckBox(peakWidget)
        self.relHeightCheck.setChecked(True)
        self.relHeightCheck.setObjectName("relHeightCheck")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.relHeightCheck)
        self.relHeight = QtWidgets.QDoubleSpinBox(peakWidget)
        self.relHeight.setMaximum(1.0)
        self.relHeight.setSingleStep(0.1)
        self.relHeight.setProperty("value", 0.5)
        self.relHeight.setObjectName("relHeight")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.relHeight)
        self.prevalenceMinCheck = QtWidgets.QCheckBox(peakWidget)
        self.prevalenceMinCheck.setChecked(True)
        self.prevalenceMinCheck.setObjectName("prevalenceMinCheck")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.prevalenceMinCheck)
        self.prevalenceMin = QtWidgets.QDoubleSpinBox(peakWidget)
        self.prevalenceMin.setObjectName("prevalenceMin")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.prevalenceMin)
        self.prevalenceMaxCheck = QtWidgets.QCheckBox(peakWidget)
        self.prevalenceMaxCheck.setChecked(True)
        self.prevalenceMaxCheck.setObjectName("prevalenceMaxCheck")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.prevalenceMaxCheck)
        self.prevalenceMax = QtWidgets.QDoubleSpinBox(peakWidget)
        self.prevalenceMax.setProperty("value", 5.0)
        self.prevalenceMax.setObjectName("prevalenceMax")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.prevalenceMax)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.peakAnalyzeBtn = QtWidgets.QPushButton(peakWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peakAnalyzeBtn.sizePolicy().hasHeightForWidth())
        self.peakAnalyzeBtn.setSizePolicy(sizePolicy)
        self.peakAnalyzeBtn.setCheckable(False)
        self.peakAnalyzeBtn.setObjectName("peakAnalyzeBtn")
        self.horizontalLayout_3.addWidget(self.peakAnalyzeBtn)
        self.peakCancelBtn = QtWidgets.QPushButton(peakWidget)
        self.peakCancelBtn.setObjectName("peakCancelBtn")
        self.horizontalLayout_3.addWidget(self.peakCancelBtn)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_3)

        self.retranslateUi(peakWidget)
        self.peakLowerBoundCheck.toggled['bool'].connect(self.peakLowerBound.setEnabled)
        self.peakUpperBoundCheck.toggled['bool'].connect(self.peakUpperBound.setEnabled)
        self.widthMinCheck.toggled['bool'].connect(self.widthMin.setEnabled)
        self.widthMaxCheck.toggled['bool'].connect(self.widthMax.setEnabled)
        self.relHeightCheck.toggled['bool'].connect(self.relHeight.setEnabled)
        self.prevalenceMinCheck.toggled['bool'].connect(self.prevalenceMin.setEnabled)
        self.prevalenceMaxCheck.toggled['bool'].connect(self.prevalenceMax.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(peakWidget)
        peakWidget.setTabOrder(self.peakTypeRising, self.peakTypeFalling)
        peakWidget.setTabOrder(self.peakTypeFalling, self.peakLowerBoundCheck)
        peakWidget.setTabOrder(self.peakLowerBoundCheck, self.peakLowerBound)
        peakWidget.setTabOrder(self.peakLowerBound, self.peakUpperBoundCheck)
        peakWidget.setTabOrder(self.peakUpperBoundCheck, self.peakUpperBound)
        peakWidget.setTabOrder(self.peakUpperBound, self.widthMinCheck)
        peakWidget.setTabOrder(self.widthMinCheck, self.widthMin)
        peakWidget.setTabOrder(self.widthMin, self.widthMaxCheck)
        peakWidget.setTabOrder(self.widthMaxCheck, self.widthMax)
        peakWidget.setTabOrder(self.widthMax, self.relHeightCheck)
        peakWidget.setTabOrder(self.relHeightCheck, self.relHeight)
        peakWidget.setTabOrder(self.relHeight, self.prevalenceMinCheck)
        peakWidget.setTabOrder(self.prevalenceMinCheck, self.prevalenceMin)
        peakWidget.setTabOrder(self.prevalenceMin, self.prevalenceMaxCheck)
        peakWidget.setTabOrder(self.prevalenceMaxCheck, self.prevalenceMax)
        peakWidget.setTabOrder(self.prevalenceMax, self.peakAnalyzeBtn)
        peakWidget.setTabOrder(self.peakAnalyzeBtn, self.peakCancelBtn)

    def retranslateUi(self, peakWidget):
        _translate = QtCore.QCoreApplication.translate
        peakWidget.setWindowTitle(_translate("peakWidget", "Peak Analyzer"))
        self.peakTypeBox.setTitle(_translate("peakWidget", "Peak type"))
        self.peakTypeRising.setText(_translate("peakWidget", "Rising"))
        self.peakTypeFalling.setText(_translate("peakWidget", "Falling"))
        self.label.setText(_translate("peakWidget", "Parameter"))
        self.label_2.setText(_translate("peakWidget", "Value"))
        self.peakLowerBoundCheck.setText(_translate("peakWidget", "Peak Lower Bound (nA)"))
        self.peakUpperBoundCheck.setText(_translate("peakWidget", "Peak Upper Bound (nA)"))
        self.widthMinCheck.setText(_translate("peakWidget", "Width min (us)"))
        self.widthMaxCheck.setText(_translate("peakWidget", "Width max (us)"))
        self.relHeightCheck.setText(_translate("peakWidget", "Rel height of width (0 to 1)"))
        self.prevalenceMinCheck.setText(_translate("peakWidget", "Pervalence min (nA)"))
        self.prevalenceMaxCheck.setText(_translate("peakWidget", "Prevalence max (nA)"))
        self.peakAnalyzeBtn.setText(_translate("peakWidget", "Analyze"))
        self.peakCancelBtn.setText(_translate("peakWidget", "Cancel"))
