# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer Files\peaktoolkitwidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_peakWidget(object):
    def setupUi(self, peakWidget):
        peakWidget.setObjectName("peakWidget")
        peakWidget.resize(239, 294)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(peakWidget.sizePolicy().hasHeightForWidth())
        peakWidget.setSizePolicy(sizePolicy)
        peakWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.formLayout = QtWidgets.QFormLayout(peakWidget)
        self.formLayout.setObjectName("formLayout")
        self.peakTypeBox = QtWidgets.QGroupBox(peakWidget)
        self.peakTypeBox.setObjectName("peakTypeBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.peakTypeBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.peakTypeRising = QtWidgets.QRadioButton(self.peakTypeBox)
        self.peakTypeRising.setChecked(True)
        self.peakTypeRising.setObjectName("peakTypeRising")
        self.horizontalLayout.addWidget(self.peakTypeRising)
        self.peakTypeFalling = QtWidgets.QRadioButton(self.peakTypeBox)
        self.peakTypeFalling.setObjectName("peakTypeFalling")
        self.horizontalLayout.addWidget(self.peakTypeFalling)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.peakTypeBox)
        self.label = QtWidgets.QLabel(peakWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(peakWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.peakLowerBoundCheck = QtWidgets.QCheckBox(peakWidget)
        self.peakLowerBoundCheck.setChecked(True)
        self.peakLowerBoundCheck.setObjectName("peakLowerBoundCheck")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.peakLowerBoundCheck)
        self.peakLowerBound = QtWidgets.QDoubleSpinBox(peakWidget)
        self.peakLowerBound.setMinimum(-500.0)
        self.peakLowerBound.setMaximum(500.0)
        self.peakLowerBound.setProperty("value", -10.0)
        self.peakLowerBound.setObjectName("peakLowerBound")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.peakLowerBound)
        self.peakUpperBoundCheck = QtWidgets.QCheckBox(peakWidget)
        self.peakUpperBoundCheck.setChecked(True)
        self.peakUpperBoundCheck.setObjectName("peakUpperBoundCheck")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.peakUpperBoundCheck)
        self.peakUpperBound = QtWidgets.QDoubleSpinBox(peakWidget)
        self.peakUpperBound.setMinimum(-300.0)
        self.peakUpperBound.setMaximum(300.0)
        self.peakUpperBound.setObjectName("peakUpperBound")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.peakUpperBound)
        self.widthMinCheck = QtWidgets.QCheckBox(peakWidget)
        self.widthMinCheck.setChecked(True)
        self.widthMinCheck.setObjectName("widthMinCheck")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.widthMinCheck)
        self.widthMin = QtWidgets.QDoubleSpinBox(peakWidget)
        self.widthMin.setMaximum(10000000000.0)
        self.widthMin.setSingleStep(5.0)
        self.widthMin.setObjectName("widthMin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.widthMin)
        self.widthMaxCheck = QtWidgets.QCheckBox(peakWidget)
        self.widthMaxCheck.setChecked(True)
        self.widthMaxCheck.setObjectName("widthMaxCheck")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.widthMaxCheck)
        self.widthMax = QtWidgets.QDoubleSpinBox(peakWidget)
        self.widthMax.setMaximum(1000000000.0)
        self.widthMax.setSingleStep(5.0)
        self.widthMax.setObjectName("widthMax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.widthMax)
        self.relHeightCheck = QtWidgets.QCheckBox(peakWidget)
        self.relHeightCheck.setChecked(True)
        self.relHeightCheck.setObjectName("relHeightCheck")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.relHeightCheck)
        self.relHeight = QtWidgets.QDoubleSpinBox(peakWidget)
        self.relHeight.setMaximum(1.0)
        self.relHeight.setSingleStep(0.1)
        self.relHeight.setProperty("value", 0.5)
        self.relHeight.setObjectName("relHeight")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.relHeight)
        self.prominenceMinCheck = QtWidgets.QCheckBox(peakWidget)
        self.prominenceMinCheck.setChecked(True)
        self.prominenceMinCheck.setObjectName("prominenceMinCheck")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.prominenceMinCheck)
        self.prominenceMin = QtWidgets.QDoubleSpinBox(peakWidget)
        self.prominenceMin.setMaximum(500.0)
        self.prominenceMin.setObjectName("prominenceMin")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.prominenceMin)
        self.prominenceMaxCheck = QtWidgets.QCheckBox(peakWidget)
        self.prominenceMaxCheck.setChecked(True)
        self.prominenceMaxCheck.setObjectName("prominenceMaxCheck")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.prominenceMaxCheck)
        self.prominenceMax = QtWidgets.QDoubleSpinBox(peakWidget)
        self.prominenceMax.setMaximum(500.0)
        self.prominenceMax.setProperty("value", 5.0)
        self.prominenceMax.setObjectName("prominenceMax")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.prominenceMax)
        self.distanceMinCheck = QtWidgets.QCheckBox(peakWidget)
        self.distanceMinCheck.setCheckable(True)
        self.distanceMinCheck.setChecked(True)
        self.distanceMinCheck.setObjectName("distanceMinCheck")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.distanceMinCheck)
        self.distanceMin = QtWidgets.QDoubleSpinBox(peakWidget)
        self.distanceMin.setSuffix("")
        self.distanceMin.setDecimals(3)
        self.distanceMin.setMaximum(10000000.0)
        self.distanceMin.setProperty("value", 1.0)
        self.distanceMin.setObjectName("distanceMin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.distanceMin)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.peakAnalyzeBtn = QtWidgets.QPushButton(peakWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peakAnalyzeBtn.sizePolicy().hasHeightForWidth())
        self.peakAnalyzeBtn.setSizePolicy(sizePolicy)
        self.peakAnalyzeBtn.setCheckable(False)
        self.peakAnalyzeBtn.setObjectName("peakAnalyzeBtn")
        self.horizontalLayout_3.addWidget(self.peakAnalyzeBtn)
        self.peakCancelBtn = QtWidgets.QPushButton(peakWidget)
        self.peakCancelBtn.setObjectName("peakCancelBtn")
        self.horizontalLayout_3.addWidget(self.peakCancelBtn)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_3)

        self.retranslateUi(peakWidget)
        self.peakLowerBoundCheck.toggled['bool'].connect(self.peakLowerBound.setEnabled)
        self.peakUpperBoundCheck.toggled['bool'].connect(self.peakUpperBound.setEnabled)
        self.widthMinCheck.toggled['bool'].connect(self.widthMin.setEnabled)
        self.widthMaxCheck.toggled['bool'].connect(self.widthMax.setEnabled)
        self.relHeightCheck.toggled['bool'].connect(self.relHeight.setEnabled)
        self.prominenceMinCheck.toggled['bool'].connect(self.prominenceMin.setEnabled)
        self.prominenceMaxCheck.toggled['bool'].connect(self.prominenceMax.setEnabled)
        self.distanceMinCheck.toggled['bool'].connect(self.distanceMin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(peakWidget)
        peakWidget.setTabOrder(self.peakTypeRising, self.peakTypeFalling)
        peakWidget.setTabOrder(self.peakTypeFalling, self.peakLowerBoundCheck)
        peakWidget.setTabOrder(self.peakLowerBoundCheck, self.peakLowerBound)
        peakWidget.setTabOrder(self.peakLowerBound, self.peakUpperBoundCheck)
        peakWidget.setTabOrder(self.peakUpperBoundCheck, self.peakUpperBound)
        peakWidget.setTabOrder(self.peakUpperBound, self.widthMinCheck)
        peakWidget.setTabOrder(self.widthMinCheck, self.widthMin)
        peakWidget.setTabOrder(self.widthMin, self.widthMaxCheck)
        peakWidget.setTabOrder(self.widthMaxCheck, self.widthMax)
        peakWidget.setTabOrder(self.widthMax, self.relHeightCheck)
        peakWidget.setTabOrder(self.relHeightCheck, self.relHeight)
        peakWidget.setTabOrder(self.relHeight, self.prominenceMinCheck)
        peakWidget.setTabOrder(self.prominenceMinCheck, self.prominenceMin)
        peakWidget.setTabOrder(self.prominenceMin, self.prominenceMaxCheck)
        peakWidget.setTabOrder(self.prominenceMaxCheck, self.prominenceMax)
        peakWidget.setTabOrder(self.prominenceMax, self.peakAnalyzeBtn)

    def retranslateUi(self, peakWidget):
        _translate = QtCore.QCoreApplication.translate
        peakWidget.setWindowTitle(_translate("peakWidget", "Peak Analyzer"))
        self.peakTypeBox.setTitle(_translate("peakWidget", "Peak type"))
        self.peakTypeRising.setText(_translate("peakWidget", "Rising"))
        self.peakTypeFalling.setText(_translate("peakWidget", "Falling"))
        self.label.setText(_translate("peakWidget", "Parameter"))
        self.label_2.setText(_translate("peakWidget", "Value"))
        self.peakLowerBoundCheck.setText(_translate("peakWidget", "Peak Lower Bound (nA)"))
        self.peakUpperBoundCheck.setText(_translate("peakWidget", "Peak Upper Bound (nA)"))
        self.widthMinCheck.setText(_translate("peakWidget", "Width min (us)"))
        self.widthMaxCheck.setText(_translate("peakWidget", "Width max (us)"))
        self.relHeightCheck.setText(_translate("peakWidget", "Rel height of width (0 to 1)"))
        self.prominenceMinCheck.setText(_translate("peakWidget", "Prominence min (nA)"))
        self.prominenceMaxCheck.setText(_translate("peakWidget", "Prominence max (nA)"))
        self.distanceMinCheck.setText(_translate("peakWidget", "Distance min (ms)"))
        self.peakAnalyzeBtn.setText(_translate("peakWidget", "Analyze"))
        self.peakCancelBtn.setText(_translate("peakWidget", "Cancel"))
