# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\analysissettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalyzeForEventsDialog(object):
    def setupUi(self, AnalyzeForEventsDialog):
        AnalyzeForEventsDialog.setObjectName("AnalyzeForEventsDialog")
        AnalyzeForEventsDialog.resize(350, 131)
        self.verticalLayout = QtWidgets.QVBoxLayout(AnalyzeForEventsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_enableSaveReport = QtWidgets.QCheckBox(AnalyzeForEventsDialog)
        self.checkBox_enableSaveReport.setText("")
        self.checkBox_enableSaveReport.setChecked(True)
        self.checkBox_enableSaveReport.setObjectName("checkBox_enableSaveReport")
        self.gridLayout.addWidget(self.checkBox_enableSaveReport, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(AnalyzeForEventsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(AnalyzeForEventsDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_threshold = QtWidgets.QLineEdit(AnalyzeForEventsDialog)
        self.lineEdit_threshold.setObjectName("lineEdit_threshold")
        self.horizontalLayout.addWidget(self.lineEdit_threshold)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_nA = QtWidgets.QRadioButton(AnalyzeForEventsDialog)
        self.radioButton_nA.setChecked(True)
        self.radioButton_nA.setObjectName("radioButton_nA")
        self.verticalLayout_2.addWidget(self.radioButton_nA)
        self.radioButton_pctBaseline = QtWidgets.QRadioButton(AnalyzeForEventsDialog)
        self.radioButton_pctBaseline.setObjectName("radioButton_pctBaseline")
        self.verticalLayout_2.addWidget(self.radioButton_pctBaseline)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(AnalyzeForEventsDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.checkBox_enableSubeventStateDetection = QtWidgets.QCheckBox(AnalyzeForEventsDialog)
        self.checkBox_enableSubeventStateDetection.setText("")
        self.checkBox_enableSubeventStateDetection.setChecked(True)
        self.checkBox_enableSubeventStateDetection.setObjectName("checkBox_enableSubeventStateDetection")
        self.gridLayout.addWidget(self.checkBox_enableSubeventStateDetection, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AnalyzeForEventsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AnalyzeForEventsDialog)
        self.buttonBox.accepted.connect(AnalyzeForEventsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AnalyzeForEventsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AnalyzeForEventsDialog)

    def retranslateUi(self, AnalyzeForEventsDialog):
        _translate = QtCore.QCoreApplication.translate
        AnalyzeForEventsDialog.setWindowTitle(_translate("AnalyzeForEventsDialog", "Analyze for Events"))
        self.label.setText(_translate("AnalyzeForEventsDialog", "Threshold"))
        self.label_3.setText(_translate("AnalyzeForEventsDialog", "Save Report"))
        self.radioButton_nA.setText(_translate("AnalyzeForEventsDialog", "nA"))
        self.radioButton_pctBaseline.setText(_translate("AnalyzeForEventsDialog", "% Baseline"))
        self.label_2.setText(_translate("AnalyzeForEventsDialog", "Subevent States"))
