# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ivselection.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoIVSelectDialog(object):
    def setupUi(self, AutoIVSelectDialog):
        AutoIVSelectDialog.setObjectName("AutoIVSelectDialog")
        AutoIVSelectDialog.resize(337, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AutoIVSelectDialog.sizePolicy().hasHeightForWidth())
        AutoIVSelectDialog.setSizePolicy(sizePolicy)
        AutoIVSelectDialog.setMinimumSize(QtCore.QSize(300, 100))
        self.horizontalLayoutWidget = QtWidgets.QWidget(AutoIVSelectDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 331, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(40, 0, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.offsetLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.offsetLineEdit.setObjectName("offsetLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.offsetLineEdit)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.startLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.startLineEdit.setObjectName("startLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.startLineEdit)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.endLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.endLineEdit.setObjectName("endLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.endLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AutoIVSelectDialog)
        self.buttonBox.rejected.connect(AutoIVSelectDialog.reject) # type: ignore
        self.buttonBox.accepted.connect(AutoIVSelectDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AutoIVSelectDialog)

    def retranslateUi(self, AutoIVSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        AutoIVSelectDialog.setWindowTitle(_translate("AutoIVSelectDialog", "Set Auto IV Selection Parameters"))
        self.label.setText(_translate("AutoIVSelectDialog", "offset (ms)"))
        self.offsetLineEdit.setText(_translate("AutoIVSelectDialog", "0"))
        self.label_2.setText(_translate("AutoIVSelectDialog", "start (ms)"))
        self.startLineEdit.setText(_translate("AutoIVSelectDialog", "400"))
        self.label_3.setText(_translate("AutoIVSelectDialog", "end (ms)"))
        self.endLineEdit.setText(_translate("AutoIVSelectDialog", "800"))
