# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\loadfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadFileDialog(object):
    def setupUi(self, LoadFileDialog):
        LoadFileDialog.setObjectName("LoadFileDialog")
        LoadFileDialog.resize(320, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadFileDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(LoadFileDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_DataFilePath = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_DataFilePath.setObjectName("plainTextEdit_DataFilePath")
        self.verticalLayout_3.addWidget(self.plainTextEdit_DataFilePath)
        self.pushButton_Browse = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.verticalLayout_3.addWidget(self.pushButton_Browse)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(LoadFileDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(LoadFileDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_ADC_Samplerate = QtWidgets.QLineEdit(LoadFileDialog)
        self.lineEdit_ADC_Samplerate.setObjectName("lineEdit_ADC_Samplerate")
        self.gridLayout.addWidget(self.lineEdit_ADC_Samplerate, 0, 1, 1, 1)
        self.lineEdit_LPFilter = QtWidgets.QLineEdit(LoadFileDialog)
        self.lineEdit_LPFilter.setObjectName("lineEdit_LPFilter")
        self.gridLayout.addWidget(self.lineEdit_LPFilter, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoadFileDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LoadFileDialog)
        self.buttonBox.accepted.connect(LoadFileDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LoadFileDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoadFileDialog)

    def retranslateUi(self, LoadFileDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadFileDialog.setWindowTitle(_translate("LoadFileDialog", "Load File"))
        self.groupBox.setTitle(_translate("LoadFileDialog", "File"))
        self.pushButton_Browse.setText(_translate("LoadFileDialog", "Browse..."))
        self.label.setText(_translate("LoadFileDialog", "Amplifier ADC Samplerate (kHz)"))
        self.label_2.setText(_translate("LoadFileDialog", "Lowpass Filter (kHz)"))
