# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\subeventstatesettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubeventStateDetectionSettingsDialog(object):
    def setupUi(self, SubeventStateDetectionSettingsDialog):
        SubeventStateDetectionSettingsDialog.setObjectName("SubeventStateDetectionSettingsDialog")
        SubeventStateDetectionSettingsDialog.resize(377, 211)
        self.verticalLayout = QtWidgets.QVBoxLayout(SubeventStateDetectionSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_MinStateDuration = QtWidgets.QLineEdit(SubeventStateDetectionSettingsDialog)
        self.lineEdit_MinStateDuration.setObjectName("lineEdit_MinStateDuration")
        self.gridLayout.addWidget(self.lineEdit_MinStateDuration, 0, 1, 1, 1)
        self.lineEdit_CUSUMThresh = QtWidgets.QLineEdit(SubeventStateDetectionSettingsDialog)
        self.lineEdit_CUSUMThresh.setObjectName("lineEdit_CUSUMThresh")
        self.gridLayout.addWidget(self.lineEdit_CUSUMThresh, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(SubeventStateDetectionSettingsDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_CUSUMStepSize = QtWidgets.QLineEdit(SubeventStateDetectionSettingsDialog)
        self.lineEdit_CUSUMStepSize.setObjectName("lineEdit_CUSUMStepSize")
        self.gridLayout.addWidget(self.lineEdit_CUSUMStepSize, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(SubeventStateDetectionSettingsDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_WinOfSmoothing = QtWidgets.QLineEdit(SubeventStateDetectionSettingsDialog)
        self.lineEdit_WinOfSmoothing.setObjectName("lineEdit_WinOfSmoothing")
        self.gridLayout.addWidget(self.lineEdit_WinOfSmoothing, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(SubeventStateDetectionSettingsDialog)
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_MaxNumOfStates = QtWidgets.QLineEdit(SubeventStateDetectionSettingsDialog)
        self.lineEdit_MaxNumOfStates.setObjectName("lineEdit_MaxNumOfStates")
        self.gridLayout.addWidget(self.lineEdit_MaxNumOfStates, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(SubeventStateDetectionSettingsDialog)
        self.label_5.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(SubeventStateDetectionSettingsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(SubeventStateDetectionSettingsDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_MergeBlockadeThresh = QtWidgets.QLineEdit(SubeventStateDetectionSettingsDialog)
        self.lineEdit_MergeBlockadeThresh.setObjectName("lineEdit_MergeBlockadeThresh")
        self.gridLayout.addWidget(self.lineEdit_MergeBlockadeThresh, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SubeventStateDetectionSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SubeventStateDetectionSettingsDialog)
        self.buttonBox.accepted.connect(SubeventStateDetectionSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SubeventStateDetectionSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SubeventStateDetectionSettingsDialog)

    def retranslateUi(self, SubeventStateDetectionSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SubeventStateDetectionSettingsDialog.setWindowTitle(_translate("SubeventStateDetectionSettingsDialog", "Subevent State Detection Settings"))
        self.lineEdit_MinStateDuration.setText(_translate("SubeventStateDetectionSettingsDialog", "200"))
        self.lineEdit_CUSUMThresh.setText(_translate("SubeventStateDetectionSettingsDialog", "30"))
        self.label_2.setText(_translate("SubeventStateDetectionSettingsDialog", "Window of Smoothing (us)"))
        self.lineEdit_CUSUMStepSize.setText(_translate("SubeventStateDetectionSettingsDialog", "10"))
        self.label_3.setText(_translate("SubeventStateDetectionSettingsDialog", "Maximal Number of \n"
"States Before Merging"))
        self.lineEdit_WinOfSmoothing.setText(_translate("SubeventStateDetectionSettingsDialog", "100"))
        self.label_4.setText(_translate("SubeventStateDetectionSettingsDialog", "CUSUM `threshold`"))
        self.lineEdit_MaxNumOfStates.setText(_translate("SubeventStateDetectionSettingsDialog", "16"))
        self.label_5.setText(_translate("SubeventStateDetectionSettingsDialog", "CUSUM `stepsize`"))
        self.label.setText(_translate("SubeventStateDetectionSettingsDialog", "Minimal State Duration (us)"))
        self.label_6.setText(_translate("SubeventStateDetectionSettingsDialog", "Blockade Threshold \n"
"for Merging"))
        self.lineEdit_MergeBlockadeThresh.setText(_translate("SubeventStateDetectionSettingsDialog", "0.02"))
